name: Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        Discord.Token: ${{ secrets.DISCORD_TOKEN }}
        PinballApi.IFPAApiKey: ${{ secrets.IFPA_API_KEY }}
        OPDB.OPDBToken: ${{ secrets.OPDB_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/ifpa-companion-discord:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/ifpa-companion-discord:latest
